# name of your application
APPLICATION = iotproject

# platform for which the application will be built
PLATFORM ?= octa
PRINT_FLOATS = 1

SHIELDS += Murata
MURATA_CONNECTOR = 2

LORAWAN_APPLICATION = iowttn
# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core
