name: jlink
root: ./
pre_window: 
startup_window: jlink
windows:
  - jlink:
      layout: even-horizontal
      panes:
        - tmux resize-pane -L 45;jlinkexe -device STM32L496ZG -if SWD -speed 4000 -autoconnect 1
        - cd ~/git/iotprojectg2/device/applications/iotproject 
  - service:
      layout: even-vertical
      panes:
        - read && tmux detach && tmux kill-window -t service
